window.AtlesContextView=(()=>{
  'use strict';
  const model=window.ATLES_MODEL;
  const context=window.ATLES_CONTEXT;
  const cards=window.ATLES_DATA.cards;
  const roles=Object.fromEntries(model.roles.map(x=>[x.id,x]));
  const processes=Object.fromEntries(model.processes.map(x=>[x.id,x]));
  const sources=Object.fromEntries(model.sources.map(x=>[x.id,x]));
  const assignments=Object.fromEntries(model.cards.map(x=>[x.id,x]));
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const names=ids=>(ids||[]).map(id=>roles[id]?.name||id).join(' · ');
  const roleLinks=ids=>(ids||[]).map(id=>`<a href="#context/actors/${esc(id)}">${esc(roles[id]?.name||id)}</a>`).join(' · ');
  const cardLinks=ids=>`<div class="dep-links">${ids.map(id=>`<a href="#card/${esc(id)}" aria-label="${esc(id+' · '+cards.find(c=>c.id===id)?.title)}">${esc(id)}</a>`).join('')}</div>`;
  const refs=items=>(items||[]).map(s=>{const source=sources[s.id];return source?`<p><a href="#sources?source=${esc(s.id)}">${esc(source.title)}</a> · ${esc(s.locator)}<br>${esc(model.states[s.state]||s.state)}</p>`:''}).join('');
  const related=(kind,id)=>model.cards.filter(c=>kind==='actor'?[...c.coordinator,...c.executors,...c.validators].includes(id):[c.processId,...c.relatedProcessIds].includes(id)).map(c=>c.id);
  function nav(active){return `<nav class="context-nav" aria-label="Dins del context CTTI">${[['actors','Actors'],['processes','Processos'],['coverage','Àmbits observats'],['guide','Guia i pilots'],['architecture','Com encaixen']].map(([id,label])=>`<a href="#context/${id}" ${id===active?'aria-current="page"':''}>${label}</a>`).join('')}</nav>`;}
  function shell(active,title,body){return `<div class="wrap"><div class="section-head"><div><p class="eyebrow">Context CTTI</p><h1>${esc(title)}</h1></div><a class="link" href="#atlas">Explora les fitxes →</a></div>${nav(active)}${body}</div>`;}
  function actors(focus){return shell('actors','Qui hi intervé',`<p class="context-intro">${esc(model.intro)}</p><div class="context-summary"><p><b>El CdC lidera la resposta als incidents d’alt impacte dins l’abast previst. Cada equip tècnic actua en el seu àmbit.</b></p><p>El govern de l’observabilitat, la gestió de les eines i l’operació dels serveis tenen funcions diferents. El mapa les relaciona amb les idees d’Atos.</p><a href="#context/processes">Segueix el recorregut dels processos →</a></div>${[...new Set(model.roles.map(r=>r.group))].map(group=>`<section class="actor-category"><h2 class="eyebrow">${esc(group)}</h2><div class="context-grid">${model.roles.filter(r=>r.group===group).map(r=>`<details class="context-item" id="actor-${r.id}" ${focus===r.id?'open':''}><summary><span>${esc(r.name)}</span></summary><p>${esc(r.role)}</p><a class="link" href="#atlas?actor=${r.id}">Veure les ${related('actor',r.id).length} fitxes relacionades →</a><p><a class="link" href="#relations?entry=actor&actor=${r.id}">Veure les relacions al mapa →</a></p><div class="source-details">${refs(r.sources)}</div></details>`).join('')}</div></section>`).join('')}<p class="notice-inline">${esc(model.assignmentNote)} ${esc(model.sourceNote)}</p>`);}
  function processPage(focus){return shell('processes','Del servei a la resposta',`<p class="context-intro">Cada idea millora una part del recorregut. Tria el procés que vols treballar per veure les fitxes i els equips que hi intervenen.</p><div class="context-summary"><p>${esc(context.scope.relation)}</p><p>Una incidència del servei i una pèrdua de visibilitat poden coincidir. Es vinculen, però cada part necessita el seu responsable i la seva prova de recuperació.</p></div><div class="context-grid">${model.processes.map(p=>`<article class="context-item" id="process-${p.id}"><h2>${esc(p.name)}</h2><p>${esc(p.description)}</p><a class="link" href="#atlas?process=${p.id}">Veure les ${related('process',p.id).length} fitxes relacionades →</a></article>`).join('')}</div><p class="notice-inline">Lectura de processos proposada per Atos. Els circuits i les validacions concrets es contrasten per servei.</p>`);}
  function coverage(){const d=context.scope;return shell('coverage','Què observaríem, i amb què',`<p class="context-intro">${esc(d.intro)}</p><p class="notice-inline">${esc(d.limit)}</p><div class="scope-grid">${d.domains.map(x=>`<details class="scope-domain context-item" id="domain-${x.code}"><summary><span><small>${esc(x.code)}</small>${esc(x.name)}</span></summary><p><b>Abast de referència.</b> ${esc(x.assets)}</p><p><b>Equips implicats.</b> ${esc(x.actors)}</p><p><b>Atos proposa.</b> ${esc(x.observation)}</p><p class="note">Per comprovar: ${esc(x.check)}</p>${cardLinks(x.cards)}</details>`).join('')}</div><details class="source-details"><summary>Com comprovaríem la cobertura real</summary><p>${esc(d.validation)}</p><p>${esc(d.source)}</p></details>`);}
  function wrapExisting(html,active){const end=html.indexOf('</div><p class="arch-intro">');if(end!==-1)return html.slice(0,end+6)+nav(active)+html.slice(end+6);const marker='<div class="guide-grid">';return html.replace(marker,nav(active)+marker);}
  function bar(id){const a=assignments[id];if(!a)return '';return `<div class="card-context-bar"><span>Procés: <a href="#context/processes/${a.processId}">${esc(processes[a.processId].name)}</a></span><span>Coordinació proposada: ${roleLinks(a.coordinator)}</span></div>`;}
  function fit(id){const a=assignments[id];if(!a)return '';return `<section class="context-fit"><h2>Encaix amb el CTTI</h2><p><b>Punt de partida.</b> ${esc(a.baseCtti)}</p><p><b>Què hi aporta Atos.</b> ${esc(a.contribution)}</p><dl class="role-list"><dt>Coordina</dt><dd>${roleLinks(a.coordinator)}</dd><dt>Executa i manté</dt><dd>${roleLinks(a.executors)}</dd><dt>Valida segons abast</dt><dd>${roleLinks(a.validators)}</dd><dt>Prova del resultat</dt><dd>${esc(a.evidence)}</dd></dl><p class="note">Participants proposats per al pilot; les validacions segueixen el circuit de cada servei.</p><details class="source-details"><summary>Abast i fonts del CTTI</summary>${context.scope.cardNotes[id]?`<p>${esc(context.scope.cardNotes[id])}</p>`:''}${refs(a.sources)}<a class="link" href="#context/coverage">Consulta els àmbits observats →</a></details></section>`;}
  function meeting(id){const a=assignments[id];return a?`<div class="meeting-context"><p><b>Base CTTI.</b> ${esc(a.baseCtti)}</p><p><b>Coordinació proposada:</b> ${esc(names(a.coordinator))}. <a href="#context/actors/${a.coordinator[0]}">Actors i procés →</a></p><p><b>Comprovació:</b> ${esc(a.evidence)}</p></div>`:'';}
  function plain(id){const a=assignments[id];if(!a)return '';return `Encaix amb el CTTI\n\nProcés: ${processes[a.processId].name}\nBase: ${a.baseCtti}\nAportació d’Atos: ${a.contribution}\nCoordinació proposada: ${names(a.coordinator)}\nExecuta i manté: ${names(a.executors)}\nValida segons abast: ${names(a.validators)}\nProva del resultat: ${a.evidence}\n${model.assignmentNote}\n\nFonts CTTI\n${a.sources.map(s=>`- ${sources[s.id].title}. ${s.locator}. ${model.states[s.state]}.`).join('\n')}`;}
  function search(id){const a=assignments[id];if(!a)return '';return JSON.stringify([a,names([...a.coordinator,...a.executors,...a.validators]),processes[a.processId],...a.relatedProcessIds.map(p=>processes[p]),context.scope.cardNotes[id],...context.scope.domains.filter(d=>d.cards.includes(id))]);}
  return {model,roles,processes,sources,assignments,nav,actors,processPage,coverage,wrapExisting,bar,fit,meeting,plain,search,related,refs};
})();
